server:
  port: 83

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.41.100/travel
    username: root
    password: 1234
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    #??????????
    map-underscore-to-camel-case: false
    #??sql??
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
